apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-password-secret
stringData:
    password: ENC[AES256_GCM,data:1wnu6GrkojMt,iv:qEFUpY1NgApA9LLMh5NJWBlLur8w52t5g/YhKD0Roag=,tag:HPgOsX90hf63zERaZCRBmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZEdoMzZqb3FkeWZrcm1p
            MW5IdTJlb0UrRXFzb2tacXcxanYrb0hyYURVCmlBRkNpcnBtQjc0ejg4MGI0QzRt
            NzhrY1BubVM5dEJDKzhsYm8yRXN3TFkKLS0tIElBTlFiNzZDalhZTUU2Nnh6NjRm
            U01YTTVnZ1F2dkhNYWhVYWJscnNrR1kKawC0yP7akB09n6qGOjd0N+78hvxYi/GX
            rcQBen37h+8vZBWdp9b02R0awlGKG4ZeyT/i7LND41Eu4nf8rxKvzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:52:28Z"
    mac: ENC[AES256_GCM,data:bCJxWhGdWIo7xyN4R1zEb0KbWSugty88b/wDM4uzw9O7WnwfJunRCLui56pjtBxhhMgC+F2VgIN/mgriVR9DcKJzf2gcIQEJPT6vm85xeSaqJoWm8AaMQQ5uJZ4yHuuPc3/d8bQVVFEGWFC3ymKWInhqtVPxmZ5ySDB4HqNd41k=,iv:nSJLnzqyisvBUosvGPf8fCaj6vGKRo1V9toy39Kno/4=,tag:rFxBvRqKlGl/7Gz0CZtMHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
