apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-password-secret
stringData:
    password: ENC[AES256_GCM,data:h3Ma/Evj22zP,iv:Lvu+TWWfkmxeV2cij5eZKUK/07JPdH4J9rsmCscwErE=,tag:9o00ElGaPJU+bLqEFti4TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UUpmcnk3ZS9iamxoelVo
            NmFRZW53eHEyejkwSGQ4c1ljTVllMWs3UlM4CmNWbUtCdmExb3BzelB6cWRCUWM5
            UExBOFJMRlR2WVpwUEd5VDBuNU4xbDQKLS0tIGNTSmx5anprQzNOQkpjem9UNHpE
            cVBuR2prVjdUMjFpeFFKTFJ6TkxGdTgKVCHOaPR8xlcjorUmAa4InH4gZe/89bcz
            x0amWf/dUvXF7PjwLgUQyQGnpBP7FPYtgxuxvL9ZnMZyP4iaV89esw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:12:54Z"
    mac: ENC[AES256_GCM,data:om62C9vcp29OOQ8vKMKVOJ+TGrqr8unnl0iy2Zmr46wHHpBPihYEYjpZVMCjY9ToG5V23W2Zx4YNECfq/sYNMryTjqbv35i/Rkkh0AMlzg+VJyp0axYYd/7esPvcqtGOO6D/xqXcOrWpEYRFeV+21RvPR+ILLeU+Avf9R/2JHOk=,iv:YrwI0T25Wq1J3FTNeNr5zCqoVy7NiW/2rhLWtQIoRWg=,tag:0wnDQD4pHg+dptwmYUSxhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
