apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:pNoofbEPP6hBy4GYVhdQI5WmjYwY56h3AzTNiruATaIMv9fz,iv:Oygiv61YoqnxXkR64zAaQS5reC5z3ZYYIL90C+Pp2mk=,tag:I9PwqP+WdoXSQYPlxKZbqw==,type:str]
    credentials.json: ENC[AES256_GCM,data:LRi1KnLRo/iT5hf+X8RERbVFNHscLGXWkiQXI+Nar8/xAbHmv0PMMKmQVVhxTfznjNkQg1NIkpshghJa0PO2uOk2a0kBF0CH0dTNpi53eIAtGvyrS5jJdO3hjDZaVe17w8NWEzr7TgQvDvzpEAOzU9xfswmDH+3JntwWimyqRW76ScrRHWefgeJ+ykRAZtd/gxuebuIcJBwBCnIr/3L9L2TJdeU3zMma3+feCq4vJg==,iv:RuIUsS9d6AD7QBmc2KxnLwF/X+vyg9B5NWZBkwkShtQ=,tag:mOUZbOVfdI/Umqn641XzNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aTdjSitSdVpKMCtCckZ0
            amxMd2ZEUGw4cmNPTHN0eUZLTGcvdlN1dnpjCmFwNnB4TkNJTDdQRmtwV3pWbHJ5
            L01OS0l5TU4zWDNaN3liZ1hEYUJOLzAKLS0tIEJyVTk5Um1GMUVJU1RETXlwWnVE
            ZmdMVS9jZkQzNVR3NkxweHlqanhrMmcKjfw69Z8hHvQX8wqAVI0O9FHI8hodbHG9
            bmA/AAAsPWI2V4dHMhBa9U7H6n50vbdst2mC6tnd0s/5rfHkRVcL9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:52:28Z"
    mac: ENC[AES256_GCM,data:y4JBqSARNx1nEWZuhOKneHQTxhRS+ok/UdkBeU9PYqma4Hgpw1hDUk5WAJrrAlaPQne8mKyJi9XyHa+o7XvJwiVwKXSXrqlP16hNMLtMrDkkbFv4yL5ZA9XJG5G/TY3zjrMxOKN3Ktce1fu3Gpj37JWgzt+QeTJd5TuukIL7MkE=,iv:2yFEeuIAIKJLYMQ8/Nz2ONQEy3Qi4/eSeTDYZe6AYPc=,tag:zEtYLZ0+gvzieRcPK5zXLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
