apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:GOd5vqHd7vxWSLR57Q4RjObm7FKz08M8eoCnFLaF0+QMneP3,iv:VfHqKbhdtSNclweO4kswMG6VcumADyXj1d8Zia9rGKk=,tag:bi61eph407c84T4L+JDsfw==,type:str]
    credentials.json: ENC[AES256_GCM,data:78Xf/X+UMgatQJko4eJFtBxneW6lad5V+QMKM2fTafS7UB1CUY5+TivXfyiuaRyxFBF5ZitbHa0Ax9zjhMAMD/jvP0LwfWOkUs5NV6VdtWu3RCvrulIaFT0VeNN3YexlAUNQSASjsWnjZ9KknL+X+WJD1Bg35wg01/EbccwWz7PCv5TsdGKry8iqTuGttGU+aSTGUAKhnDTk4aQSy+20f/S3tcogarFMYtC/d9p0Kw==,iv:W+Lfgkg6udUZpwZW3cuh+11qhqcs8EvVtOnTqY9Sbbk=,tag:Tffi2gOMVuJxeGGcFalLRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VWU5c3VHdXZseDRLQ0Q3
            Z0JaWU8yaVBqNm9BNkVZbXhWR1lVUy91VmhzCk85WFRlM1ZsYm9paWh2VGFFaE9D
            YmdiR2NaVVpuY1FGRUdHYzVPUHhKTlEKLS0tIG43WDJDbkFMQmJ6K2N0MDJEMy9Y
            a1kxaUZLQ0U2c0s5RUNTUXB4OTdaeVEKJwLsSUoqkmkXeqa3dz2OzYFOCX02jtSv
            hCZNRujIeQMqThNWX1xQZeXZILLQQHEvJ4HDifYALemD18McAF8A1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:20:56Z"
    mac: ENC[AES256_GCM,data:mia1z1pVue09iKw/TlNisS4z8OcpichAS7eoTxey8VULksTpEJaO4SDhSr6xKUybFJIIC0lwL1nVLjKVcDOt86e7kG5/WRS2kNwZG3M2tWHmLt8exJl7d42gFG0AlSS8Z3CUdcn/JIB5rs+V26rgkUdpJqwv/gnQDoKXw6IrPBE=,iv:eg3coqma75z+8QBdnwXKlHkeMz6NjdImD4CbV35gY4I=,tag:JF2y6F5T1jHFi5sGSGcF4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
