apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:7jxYiC6RGm+TPKsvGu+5I2+IVhRtUCUKO6la6frzNTSby3Ji,iv:MZiVmrxcd07z0dUBbw2aeGcuLxH4nP6/Y+e+NiJSeIE=,tag:I5mTN4vzrSEw3tSqFemwpA==,type:str]
    credentials.json: ENC[AES256_GCM,data:4Q/txGr0efjPgCESjiUpYBVivmquXfDo9i7ndqgruz0jiEyenSUZQYQvZXCHezf6qGKZrE2AFPWFg6q4euybcX/42V8cnhNxzNl4MAuYd/kIh7xU3ksMNqEUYv6HAXuqKNQpIUiI5caWZhiLLnOH6uKK3A96T7hkbd4xCHgzJ35TvM6kPxoEktJokLjNvWsH5sr2QGOolBuskz77ZvPjlaICiukB+QrwfCmI+FzY1w==,iv:n/RBRIygUAwOWLiRM+yaAJ3r7CSq3PnqG44kdRKlwG4=,tag:MG7AKz5PDMn0/af3k16w4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndlp2Yktqa1cvMDBGZXdp
            WUNjckNSanJzakFJOGo5NjRrRFZHaG05TlhJCklCVS8xKzNEekdTYVpxd2NEeDBo
            bldvWk8zRS85blNDcGI0Z2Zma2FFVzAKLS0tIHlXTlVqUmRsZllnQ3UwZTF1N2xN
            V1l5TmhDQ3B6UExuenFENXd5S04rVGsKqADAHZq/tXWc/DqD5bNQbCW1p2jTHmDS
            BypriKCK2Q1GxCNqEJGEFGP3N9nvOJcnHeYN/AMP15M8ISG7fWOTgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:12:54Z"
    mac: ENC[AES256_GCM,data:aHInMuT43EkEwtLfCPTtd5EsoyhaWJfndbQrKbV3H3DZ9goibMJXH+OtP3mNd0qk0c9DjGM2GYFxbJ9C0z2fjOxIvAreSU/BtfCdo3Ff5ZlZXF8B+1tmmQmpFx7FcERGrTFj//zUmQKKHneIh/B0Bz9/ZaYyXYmVr4pwUp3o9Kw=,iv:lMljEIY9riWx3OCE3s/d2AwCHxKn3CTSImjzmPoaROg=,tag:0GSy0PWRlEgwJaoKNszu/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
