apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:wvmgLJ3kLCpDnO5wcu3eYO8WI94fADqy58c2C5HugRzNjfaiFaZLUw==,iv:rSVTtAXXk+1U/+d43C+XopXtSGFSYN3hYrxLi2IypZU=,tag:ovCWaQZteztxJT5uPncDfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb1RDZitUd3Z0cm5RZE1N
            c0crU2FmL2dCOE96VUdoeWUxRXdKRFZIazBNCloxQ2hrRlNZa2dvMG8zMnpVWTV1
            RTBIYjFMYUZOdkpETDRRazhMNG1CQWsKLS0tIEo5b0pBT0Y3N01IVGwvYWE5dVYw
            dmRDTkxyblNodk5walBwT01KOTJ0TzAKKkpE1n+9SgHbQ7KFh2iA+GnXh2k4T22u
            ONjC5Pt22zv5KxD2cO1cjzTu0yeQGSXHqiCubUTwx0qdQVcTyN0JQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:52:28Z"
    mac: ENC[AES256_GCM,data:pKPBY1JC6FONzOh3LYQ/m5UBjGt5Ig3SY5h5R7aawdYnlDXdViWZ3gVRsFAxZy1UfEU4z6G8GAhwoprkfI4ExS5ZPI36+bhwjxEFP99AEIyWxnFHFUNToaI5THjAMaEN9+iJUUgODxDn7+ly/MRAmC3VASp+nVsncd5e92XPx18=,iv:fv3yg8hIQQjwMGzyiUcwz9QgIzU27VJDj0hOBB/xKZo=,tag:kANLhXAfNqPypWKpGi/UaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
