apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:PZh4ENUE0qCQ2HRQLBvc9ywh/PPlocUFlAxoK5fW/r+s03QJ0pNB9w==,iv:cpnNKNlraZzj6B+dV74yaqq2tzl9A6roEOvA/qL8ZTg=,tag:58A/jdjSg3gz76awSMoo4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWUtxNWt3dmZuNGJaTkF3
            NUp3K3F6dFBYdVhuR1VmeExlMWNLKzBPQ0JjCktDNWxBWFBtaUpqcEpseUM4cWFn
            SmNkTzBiNnNBUEVSNDVjNTVNa0g3cHcKLS0tIGFVaGhYM1MwUFlmNERocFc4VURJ
            b1kwdmE5NmhleUVxM2xWb1I2RUJKeTgKwMVUiS8vaVnGq4EA/MNFbrCrvS6jThHk
            MmIrq+P7GCDvxzTcYJ0YMtDqttsF2CkVyikgMbPuEc8ChRJwiZ9bfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:12:54Z"
    mac: ENC[AES256_GCM,data:OennCnqAgTXVCxN51uoaghsg+N/k3qaqsEsHLr9WHUTBM6o0xWNNROBOTrhyyADJZ1BXUNai65EqIcWaSKexyaH4e2n8sHlz+RBqsN1FLhd8rIRLBCjGoGjCvoaBsJKGhooc1L6pA3KE4H0UsgOOmtnw1I4B8d24Y9kRc1/n/oU=,iv:7U+bZ292XD7YWhZ3+PWKux3n4d+MLsd+DkZcDsRM1LQ=,tag:SVGMwjLXCYLFSZw0eFr+Og==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
