apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:/iFdfxLD9lVP22bYsPaebT1CdNVdlZxp/2T6G6tbvhKuRiOaxZwpGA==,iv:sdm2cFfWiWgd5kMxgfX1AKW0UNfnvzRX2/y3DE0OfGI=,tag:0zIhwP/QWJLaN37xNZHQxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eEVKRGRES0hrT0czSVhM
            RGxLcmJZWkJVaGd0MU8xTlRpaHJuNXpIc3l3Ci9kRUJxQitKSzUxc0lLOEFzUStQ
            M0FTN0g5Y2d4SzM0YTNEcmNsTE9zSXcKLS0tIDFYVS9lS3JBUk5IY0RvVnlYc05w
            eDJQOGw0TVdBSFJEWEg5YTM3elYrUFkKplwzm+/ReE1oIxc9zJawL1TvwzzRywyN
            L8imdCn1d3R/kdqcr6nTrNMIzczyZpkppqfTiV/YkKa2Ipc9/2MREQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:20:56Z"
    mac: ENC[AES256_GCM,data:Zdwxywt07Uq+EhJ8fWJh5ClU34GtVyvQWuQGYCwLfrDykXqKoyo28Kv2Yc71CEq0y6eyQymHBGuQqYSsUtp1A/ZlnDt8290P//mi5P8TPUEFXRq78XEVdAhW7zzJse1eRJxcv3B80HaXud+yuoBekdbNWH1PiJrxJq9B0uOULEI=,iv:Xx1AZo5yrOEUtv3uK49/W6ZVg6NtSpIt93OeCVeomlM=,tag:5Zgiv2Qf3uMAwPykTB5EvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
