# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-token
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:NwrOTjPEGdMLe5dAXrbw6nSoqg0h1WoLAkZigoRQcH81f5yF8VIbCl8iXO/biyusrKrTnNcFunR7xNT6EvpLwVbdGrjaQ1SYz7uOVk1fNZgdzHjBSXXRCqOGKHsET8UVGDzfl5+1coOLk53zK2cWGwc57WQ5OCkmauOun74S6wgGmYVCiZlkylqiidL/1lvO5Yq5ZOgliH4d1Gwvn/bj+l0WbBIHGEdRqkTZA6g4SXr+hStAc1Gq5VhUb2bsfCKOSIGGFKXK0eUgBYFI3HS99RKrrZgW3U+NOsAzd+3gJP37d3kdmWFzWQvK4S4YFoPc9Y0zk/jDfT99mHZrVeAs44YB+2aP2ORRxGJYr1kBmfLAGVCHzlw0PcEz8Hyi2mpcxuRamZNoB3Luq6xSzt17YpLmW9RqGsiWQFUovjtHbGsDXjtSUqwQVD2X51CKoaaDisU0GOjfeP1zpf4eAL9OKeBNiNLA1xsnpsHSAqgtwhx+Gz6xCGfTKj1vWobqE2d3ZX1OzvC43lRlHgWCDO8x/Bsr5sM7Uqevq+4IctmwP1Pb3sNbQYwE54e7TVWTHJDlHgXajcSdgDs/TlngM/vCUJa4Vt4KkKq55wahGhJeDmiiMGGIJc1JOVjKccuOwjmcUPyQs9psqwa0RHFiTgbUU1+jL369NpXnhgSmUB/eRBFj59B/KgUcgu6Lgp60Yi1nOlciKD93WcYi8v4QFUg70zJy3fn/QCkGaehiOiVbj87rrBlpo6yuUMmpMo4JX6HR/9+J9ditKa2bNSGOzN5s7jSb0J7sZAQPNgTLN4nMzRD1pWErwP4e7YgTrYjtIZhig4242K9NC0LH9Sg3/rNZA4fWaBAvP9d6j+QArD5qY+2SYnmpQLDp3u8Stu5+ee4MpRnlAcTai1S9BBLenQRoWs+CtdCOvC7fN/YAPRMtYyY5igcrBji888+/moU1bVJXHvdws7lYzn/US6Pm87rYXx72ugC961vYb5bPl9C5CJ2WNmC7Wb+VtaiTugQxw1dEClm/UFo4apxec6XsiGaxR53Gq93m0cw/7ZmkTZs5r0+QXnNYuiCPml1B5OacWQ0vNno3tNrbA1SF9TaNraZTNUXeR79LI0fJBDUwQ4VNHKtr2yHO+AXvcDd6obplSkp1Lbf9rtDyGDLYkX84ckHDCWSXm9FtTmw/IXoreLP2F7+hRdMndVGTJeo+VuUwismjaULIKd7hXoBssQchlNIR3HYOB7MgYcl+MaHHfzuOx1QZInyXUbO1FBcgSFH8yPcEu/0VIKruhH7P9ty++bgckPP0gS8=,iv:/qVZXHYEKKDCTLdaoVwCyYvT7sBe2ELsu5rCVfZGED4=,tag:vABNs6G5EiqP/tFI3kuz3g==,type:str]
    NORDIGEN_ID: ""
    NORDIGEN_KEY: ""
    NORDIGEN_SANDBOX: ENC[AES256_GCM,data:rDlEJRs=,iv:nL4nnk6QA5bxE1EoIrbuvnDkTDStIuHX9nDuPu5Pnug=,tag:7o7rIwzX2XQadmZdG51bNA==,type:str]
    RESPOND_TO_GOCARDLESS_LIMIT: ENC[AES256_GCM,data:QXZf8A==,iv:U6S8VcizcoJp/eg2Wkpu3zN2tCh/XtqSxApJKAfFdqU=,tag:rIWWZM+Y8wSm/EnOWtSNKw==,type:str]
    GOCARDLESS_GET_ACCOUNT_DETAILS: ENC[AES256_GCM,data:nih/4qA=,iv:iae/T96UF/DIr8P1rCe0bpri0BkmqD7u3uWD0KLKatI=,tag:Sc55uX0ZtnD5PuvcvlopTA==,type:str]
    GOCARDLESS_GET_BALANCE_DETAILS: ENC[AES256_GCM,data:6O5/5gs=,iv:MZqqKcCjfYfnrXewOL+Pk4wgm5qK7vwXn9dHcFZ072Q=,tag:PbYROAPIQ8LIWgKpV/NIAg==,type:str]
    SPECTRE_APP_ID: ""
    SPECTRE_SECRET: ""
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:QneNW6xl5ZmJRuEUDtRf/Q==,iv:EKQ0hVNctLs15AZvzMO9Yzz5H7DhplAsEgjeIEdMcJE=,tag:PpTaMJDBFElzOne3nqT3DA==,type:str]
    IMPORT_DIR_ALLOWLIST: ENC[AES256_GCM,data:IPIPexW7iNtJAmVV5/GtP2h8U3M=,iv:ZwulR6HGTlkhYFRFn8oF7B3YsWMszPOezDvk7l0F0us=,tag:wP1aAPc8PVznN1wJmcPHXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVGkxUUp3MXd1cStXTmIv
            bVpBdHJzclQySWcrS2ZXVmFYbEVaQlA1OFFRClhvMkpqSUZOTjlqSy9hZzV3c1JY
            ejJvUUkrTnpBME9GRzhLZHA0NnBMVDAKLS0tIGxvRENBeWtTaVZKVkV0RU5UaTJr
            clI1QXNpOUoyNWhuSkl0RzlWeVdXdEkKhjVJg7VA0uBv9kWEtASGr1D7z55rh6j+
            hV9ByL/DTWUaSIsXzFOFXeObq6seLbUoqeqer+2ZD4my0AesVeX7Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:20:56Z"
    mac: ENC[AES256_GCM,data:kTC4XF+u5pgQNHmJiWPsvomLPTMV8w+9c37HnEdCEMeiieko4JSfznyvw2ujXUvZSWgbRXQk0tyZFbdv/i4jCCF/HjqRMUvoWo7zQ2+I6CXj8LY2AZS5ug5dPHJPp7HhR8o9kSFau8h4ldCpUtScsx3rQkpu2d9WcENlXLEzLEc=,iv:pbusrI8pIeTGiJ/wS2YXIRBv90RqVX9t4RMoXRCDGDI=,tag:d8r516LQQIwfErCYz9ulUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
