# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-token
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:5zZFidMyEwXy2N/EKg76lNsEeo/MUmx1JqzprfF3kUifAlRXu61IiH4x/OvpFekki2gHIJoM5lDDHkk92brKylpVTryBswh74xdoT3p+wh9tNmsKW4GRPD6ZROVEUsA1lEG/yB34cIij/niWjOJRSPE7mp7v5yUIeaIOCWdHS+ViRaLTSuZwoHEker9IKQKKvIE5tVOoL9nXzedCF2VLOoR84L2NHs4FMkeEk8EJcFvs0UOg0S4hZsyqsgwlIMppDBrpFcziv/qsoh/ZN5uYLTfz/kAq1kVpBY7qtXBiVvhcMURIQQXh7IbwGGaOrcG3oALShSc/p/rQgTPm8lIALituYNvTOBHhScOzAvF0YPlP+G88czkjYFRpD6CWpw7ZA4miWFMoz1ULvyPpayCm7S+eHi0AI5pm70mQjZCGlqEwWmi1j/60dhIsUPvMUfYCXDZeIe9p3egPUgcNOisoeZR9dySHxMPqhSDVV+rexp/YYu852V2TjdDD/7swPpElMIvzKRchUS1mFdOB6G+IqDR+KfD4Y+QAasNcUph/uu3/9sv0gntohfgB8cbeR+oJNgBlwAiCEjHNJnNHnINDAkCF2WiwKlE/fQEvAqXIvxB87dFxO1tCLRy36O8ZV0uw1G4qWb6IQmj9ra4rfqcRYU81OkpS2EPkGBRDlOXEXeklQo5rKCphdBCSu9OnuPnMIHW/shFmwpbMUWak0E1B8H/lCNI3Eq5rKdyY3fFeJMKDMKZvIQviPo6OXfYDtwP6vklIg0JBkhFE7dTw/mmFbphJgY+OONJTB3ZYvisLYnFObd+TAbxEHaJGIxYtS2ZbYyvlA0PtFe279zYkhQ75Vy3yxTjkCBUzhvSP8bncD4sLynrQTcIB++n30DXmK25hNbOEm7EGgJCIVNRC23HLW23ySpiEe/o9UQqnpf6X+OjNElWhIPQFuyuiD6S7HfRg0VcteotFQ8gQz2P8hnPAXM30ES7qn0R1eRDe7rSNYRlcD+K2A73Bl/Q/lkPBp5hkk3vIMixuIaZexq8B9r2ElqjX4haODsIqvF4+QejQmvWUxhh5Ij3s0aV/bbx0AoqsNe0AkI9SeqO1l7jDF/vw5qn5u1/FXcv0C5xD329YmuGlV/YNvOLS/cQd3vfW76iVhrIxFlWEIV+tHXR/bmxnKkfcUoLyMoK9oD85NdzwjNhxkpahKWXrv9wL/viWk8Bn5j4jjUwrmM2kvvLvG9fZWNn2vrebmIAnbCXkU5j0uXIx1wcri4tvwiJRN61Vlu0cqT8eIAzO6rkjF3Umt5qgZgk7jYM=,iv:G9VZePS/XU9SF0khoO0OuK0G1KaW2c0xJCndaCrWNBE=,tag:iUgXem7PzRwRWLeLo0tcGA==,type:str]
    NORDIGEN_ID: ""
    NORDIGEN_KEY: ""
    NORDIGEN_SANDBOX: ENC[AES256_GCM,data:l0x16/k=,iv:i5OXFD+TAsRWMWuWpqtDWerLo7SZOONOQyHWb1jW8fk=,tag:N8q77e4QfNwZ2OEsEnV0XQ==,type:str]
    RESPOND_TO_GOCARDLESS_LIMIT: ENC[AES256_GCM,data:67+Lxw==,iv:XbWbEwobgKCotTt9WalGhvvMfzK24NflQQkYTwjTkcM=,tag:IgjX75wH0e65ymtE4lSCRQ==,type:str]
    GOCARDLESS_GET_ACCOUNT_DETAILS: ENC[AES256_GCM,data:PRTX8LQ=,iv:dsDfzIUmAeJqVXdKRcKlRVqaMGUWCjmovUgHOrXTmEw=,tag:xKxr1AH2TQrmX27Cqk3ZxQ==,type:str]
    GOCARDLESS_GET_BALANCE_DETAILS: ENC[AES256_GCM,data:RW3Rht0=,iv:6OqKMYJzn9MqpufwPRulwdb0uuX2KZ6YFqHYVuvHUpQ=,tag:Nk6eK6SvHzsBF5XWAWT1nA==,type:str]
    SPECTRE_APP_ID: ""
    SPECTRE_SECRET: ""
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:gYp7rO7y7WRdxvxT028kkA==,iv:SG35Ki7j7FpwwSZNCfwTZY3LqfLAbA5Bfrx4tTZl508=,tag:uv+7NxR/BTDraVNrl/B0OQ==,type:str]
    IMPORT_DIR_ALLOWLIST: ENC[AES256_GCM,data:sgRFpPlhFu5DlhwesHpnlsB4vKg=,iv:bxp1WNrQ0sz6JFOwDRmpW5ydFq8UXw1ZZZ6TqZLs4Uo=,tag:7efziJXThLkTemdqRzyEzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SmVxT294dlFQeXd3ZU90
            UVRMbFRFSSs0K04yWXBGTWE4VEJscTlSb0JZCkdSVmlncE8yWXd0LysxYlV4ZTlw
            dnkxVjFmRmJLQldyVkZUdTZZeVNYV2MKLS0tIEZtTmRjVXRPVmE5WDlCM3VTbCt6
            S2J5RFRsb3U5RzVDV1ZkNFpTb0dybXMK88UxOmODz5ly1/TTHKjCr4M70SoGwBGt
            UOuv3uWkkrLg53EV05a0RSQYvVZ0UT+j81csBUdS2ZOC1C8ADi/P5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:12:54Z"
    mac: ENC[AES256_GCM,data:ozUX5iyfws4BRKkGMKEgofp7GLO770Oa/jWqhriUb5/qOPLsZUd6siKZbemJYy14ThCf+XbrfXF6C3GpcDdsxHof86oh1faeAi/x1+iI/lVjs69m5tPdDDTrp+HI2024MW0oZOpwQ93MCnn2d1vHJinOXglhT92IFmnK1jcwPyk=,iv:Uz6AW1zzdp4PdAzOwh2BhKFI6SybySE6BX2faX2GmZg=,tag:8EMXbPhmA7BRTRJuMdTVdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
