# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-token
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:fPpk3SCx6Rd65gusbcDwsurNUIrkgmwT6HzPqKRdxWbbnAYjij+7g5NnUTH3vfXI/ksYujHaWZGTS/aEL/K74OFSaGxnSUB4ts3NeJlw6VZN80M4hxsIBiSmUvQrmrfPYnFkkHEzGyPsrrfiaSn2NiXUDbDTmeHAU7Da96i6NX5IuWu77GxgC/DSBXrKmYdLba/M/OnRmwJrcfx43jFLDBqjFzJdAhmokXJo/ehMFofioUp5q7/uVOC6TTPIe/CW5BQknlx56BzHlULP48UBfDXje1wHd6OoE4JP/IzSZDx+9JIeGv8/ZhhlyiWRMJ0Sratyc68WvoYMwpClCRcRWZLY1tTYCE+bRa1xY9TTf4eS+hmPNqZx0DJJTewA8OBwbUlMQDc9wkb9avynoUK9yKGoYmutUgD/xDBbu5hH0Pgf2VxSwY1+5/WEN3ER2CCKKRbY0e55ypxh1gNcr8y6XMJjzgDB3Tz9Z3pwT6l5suP+yAmeWf/9SqkLDV3FBwixjx+awBfan/gJ0CZQ+Sh2+ChD3DgMp/+e5fyE/tPVu0uH+6ybPfGMiUqzoSc4N75lFTXVkamniJahA2k+0vznyqQx18/p2G6tiGqr96WtNpqzTMt53ADArNigQhqHxvfyvKWect17dZF2/FQzv7ybxKp+kikbgS9YthwqAeHryKynyoPaAPzUWBsqSLfy+OsgQH8hkBmfr6luHZ5ucjWWagMD6Z4ZAE9jE6t+62t9tj1oh3IDa9Qonmn/xJr5ZB/UFdDCu4EeFXNajXY+vZbcOf3Qmn1+3r3hoq5uY9oJBHUPGFs+5HBtqo5hftyn70GmGjklBQZqtKsC/C3nxAXkmAerqei0vmpLhfOH+UpMrAJuhxKMLR2+6yzFSXxpKS7ml+zXobmt150x7/O2iYH8RW3CyXQQxczpRa6ycgGWKOVCjE1jxaeqAPFni0ybp83qJDX4yGkFpkJNAuxunCZjritHv9maKmTrkddYFd7qOuMyYpRA7+5GTq+WQHv8K0RIug+MuD8p+W39sMD5Hh5FUH1JAfjy2bveSNpC9CoOySO461jYMcC8c4uWj2nm+Rt0W4GuJN2jJ/IIKDRmt5tUyZLrf1nlwGINdNVOITw8au6xd9SLrRG9Zta/qBUVVWt3vke8rBaWLNNG0SNo5/YbFPEdBZVcPD4gtIkN1sQZvpVcm+PqY+qLkAhKGWkE0wbpI385JaquZtLDAHNq+FE55pjrEr0OCPAXGuDu2GeL0Zc/x4SGJhOvgVQofP5AWtYPEFGY4LzDqOX0sgv2zDXXpHMTwzI=,iv:LHYVuVDcZdXMzEb63RK9dM0yi72uix7WPo4LfgsUs5I=,tag:FoiESrjpci/StB11oOl3Tw==,type:str]
    NORDIGEN_ID: ""
    NORDIGEN_KEY: ""
    NORDIGEN_SANDBOX: ENC[AES256_GCM,data:m3tGPy4=,iv:N9DoLiTZnEPnS/kBu5bI0EEzyCdDIcbfilqscLHVy10=,tag:C832C3IlOtwzj+ILyI6THg==,type:str]
    RESPOND_TO_GOCARDLESS_LIMIT: ENC[AES256_GCM,data:MhqwzA==,iv:JYAsLWS6tajwQl4QE4O2n1nCxxcVz088li+ZPoH6I9E=,tag:SWCm4W9w1U1bJMqsOSBsYw==,type:str]
    GOCARDLESS_GET_ACCOUNT_DETAILS: ENC[AES256_GCM,data:Ck1kCBk=,iv:WnnPZwQSJNhZvr8GW5K1Qfiqo1/QX+MmXLaDsB05os4=,tag:qzGndG+bzvAtkvDO3vNTKw==,type:str]
    GOCARDLESS_GET_BALANCE_DETAILS: ENC[AES256_GCM,data:g2DoyVU=,iv:G6ZM0T/irYiSp9kSeYu1hCzMDh5Lv8iKVh6YE/V9aEg=,tag:U/zkGBVUoAXaGGYaF7U+BA==,type:str]
    SPECTRE_APP_ID: ""
    SPECTRE_SECRET: ""
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:dlbR0r17+MBi27RZUhfuXA==,iv:vjXyvPpiS/0yxkNYB0ce6ISDSWjrNJXrFliSSxlTbYQ=,tag:l5o2FKm7+2XM+RBEyo0NIA==,type:str]
    IMPORT_DIR_ALLOWLIST: ENC[AES256_GCM,data:xcFMUdgLk34cu0bRVG4Fr/xT5JQ=,iv:SWBJGZYZAYFKyDcjlkkUmhaez6YCYGiZFN/i6eZF4rg=,tag:rL3ySXvSaFwx0DA4cMx72g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOU11N045a1ZKSkc2U0dt
            S0U1VzZkckxITS9ISmpIN2xXUWo1Tk4wT1NvCnRIcmNxeS9UV1ZoYTZ5MzA1TW81
            OVZ0RllMSzVObDFiOCtaV0dUMkdEWEUKLS0tIG9yelgva3RtR0I1TlpVaTV1Mnpa
            bFFmYUozVXRwMTJHOXpNSjdjVlB1TFkKqseR0sxflYP/jZIanBP/TZ9Osf559xHh
            5SbPULLTWwPayIXVRj5i9ST6Ta4BeV38A7KIR2YpItFZjIl9NotTwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:52:28Z"
    mac: ENC[AES256_GCM,data:PihPEwyS/2TmlhyunXY6wYP1bxXCL34R05ssIAGHR3E0nX215Zffz77qnQMJajEin8wfj5EVuXU6ihTN/sA4z8diu88WJE4Reth2EfT9wryLsz2DZfDxwF2YMJgjUywcgibfcBBRzSbDagGAihcPhQcFDg75VLC2G14QimlpvNE=,iv:7UqOGcqsPNkfCQVh4PTWmTNz1skjqPeHCS7cRvJBbV8=,tag:DHR7uFE79T+BdiK+dLJc4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
