apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wrDr3QZIO7DEgGw=,iv:VGCr/YnRY0nghmDnseAjPmYny0CiPX92zXqpVJ/4vpI=,tag:hxUW+fre2+RxiHImftRqTw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:eqsBY4hqGT/n3k8GOA6QXkA=,iv:tSX63H5gc6KoKMiNVYa2Px9n3rZLNOoArP/ZcKhNG74=,tag:7YM2kksYLwyBjcphcrfPzQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:d23iJRhx+WYfiYTam0XBVKhFUe47TaHBKiKWaMzZ53i+6lAJ,iv:i62Cg1CHCrnMZO8F5s6Fw8iD2nqkt9QFVbGm3x6PrPY=,tag:Roswu4SlkaFxa2xfbu17ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbTUvYzRBYjRIQzBkcVhT
            dnRhNkswdzZFUVJaazJDLzcrMEIrZEw2cGlBCmliN2lxVmdrMTNneWVPZWVZT0F1
            b1hsWURtTEZVTzFoekVoTDYxRnZ4Z2MKLS0tIEpuNi9mMWlmdk14a292Z0Nlc1hy
            dFh6L0dwWXN3dWFrUDRxbmtlY2huMGsKe8q2dO7eY+VE2JGnwj+az+xAL0nkOPiN
            uaLLYGnYxTGmpFD9IkJK4bnKuGqBgCRC7NowITIDyaugSVI1TtixUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T21:20:56Z"
    mac: ENC[AES256_GCM,data:NSTwU1GrGUCIPyc0SQQxyivjUR6qI0/BxyQCziACJL0kxMeLYtEGULnUal9OS78uY8IknOM54Cy+YsCQ8OkMxttBzl23XL456Q+c5UyDJno0o8YHpiG2m1H2S8i7OrB81Rt/Nn2hgJrPljThEOz/ZgbdCQcMVNuaYcSAFcYS5C0=,iv:Z7BvbIcQl7U6luVievAL5XNRI4YGAge5DjvbWDkp2fI=,tag:ExiZQg7aB0mNbaL/9NH0yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
