apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Y3QxZ7cu0tqZNMI=,iv:bxa+XH7S8lFeiMfqxRY3DjTvclS1ftBHi3cWS33Iz2w=,tag:gnKdSndiQL6eU31aYyBhkg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:LRza3/dm7N9KG0dm7TkPeZY=,iv:T85Fc0LjTJ8J3qg8rxjuxPQiGAseb7i/sk6iEng1AYg=,tag:fhw/jAhh1mUtF7Wp2FSxKw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:EMyep7GO2SUGNojger4rrRQMzzRXMVjDx8RP2/GT3flXn2GM,iv:uIaRcm1VjyYsRvna3U1ZHhlU7S/oXPqWCt+Q107Dquk=,tag:BitXxYlMlV2ExIKqGHV69g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTzZoTm5NOUdEemF4bEEw
            Vko2LzNBcXFYaTR5bmpQNjBhbWd4VklHZlV3CkNqd2d1N2YxN3hnWmFMNnFrVjBY
            TmwybGRnenB5dy9MdDhQRXJQVkEzSmsKLS0tIGJ5MlB4QkRRMVNRa2d1YmlzN0s1
            VWM0OEg2K3I1dGliSnpKMWRkcmxVWE0KMa1za+/MY/5WLPse/KzuChT37zzehLdX
            Ie3tykuXRIbq56s2cOjCrmPh4Gpp3gQZ6iOX0Zq6+09JuaXwcBer0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:52:27Z"
    mac: ENC[AES256_GCM,data:uRfrb5IYuHICmbQU1eWuWWTZRL15dJXeYS1Z4YBChy2Bt7jo1IlCSNXVHJ4y+tbx2SeVgtKb5lyqbWQGqv+hh8vCGiPyPmACzEvRI8SUf0HJ/b1HX82TT3j1BkZmJDDKjAJZCHvSlW1nwUi7ERhxzb+GtuPZ6iCqVGxsrPpKYww=,iv:XvjjXpyLtdjAY9oXO6gl4/HnfJ3+gOlMlUaMOajj6xE=,tag:VMaxIFwCgkjMPegZtaR53w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
