apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cdSwzIlpLd2U9Dk=,iv:vucYSLMvWQX8eyV6M5P+z/XjqRy7C98PwTMtmyOy0k8=,tag:ww0QCTKstf1biF0sezn96w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:EA+WsN1PlKVyByfgRrzDDgQ=,iv:k7Z5X0LSTOvhFfl2Bib05WhbQ4QuAOQeRChtIb5NqyI=,tag:Pen408n21YMZFX/Is/L3fg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:m4KmzMVlyO2d73N11Kgi2VaHOH/h9LOObEg7CnSzCe4SDqKS,iv:7rDGi88ljoedhRAhCsJ7epYevJMMUuZuMEgLRt5lMuc=,tag:/Q1jJQ1tx+p50QNzqrZmgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RzNyeVRWVjA4Y0RqazNz
            UXk4N1g3Z05Td1VpeFgwRzdKUHlHUlhUZHdBClhWRnVMYm5yL2Y3OUdkWlEvL0JL
            RXhJSmhselN5YUcwQzl6elE0RjRUekEKLS0tIDRLekhXM2xmWFFsTUVIbGFoK0sx
            YVpIMU5xMU94d09BZXZrRlhFbVVsVXcKTeOa/v8oYeL4Fn2VOU+nDcVa6687MJPx
            pJA0/ia/rvITw5WfxGfKkh8UR+8K1o7abS+YiF2C2MZ8e3B8knt0yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:12:54Z"
    mac: ENC[AES256_GCM,data:a+x/Vc1wQUF7QWAh0iec98WudDdo+0zGrt58h9ZC1a9jem5+Z/iFLcRz67RHEz/x+6YhzZhX7Uzz9VvOmKP6b81TCRmchKPsV/9eItPlcK8vfpQ/Dp63YOaNCxtHIU5Fjz53MVmKqM+mDxPPRHatQWAlEp9Qt/GWvyufbn9VtAc=,iv:HXSkp6fdYckAsiU6ttbAtUU61F9MIO13XNoqnjFSWEY=,tag:q6MIHOqM2gOJjZ0541jLSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
