apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5qrKsT0rKOWeiYXTzj6qmyHhN3U4PZ1sn9+b/X5mi+k=,iv:IBoUJ3mvq30HmbavNy15H98f6oBzRKR7a8aHwi8GwAA=,tag:2R+xcCxz6KJLx5L8tdW0fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRGlLTVY0akNlaGFFUHoy
            amJBOGFCcThrckZIbGVWOGFoZDVDZ3d6YUNzCmJZWmo2N1lWR1VzR3dtUzJwcHMy
            SG5McE0yQWVJdHhScDBteHBlMHRjZDQKLS0tIEYwRithVFV6cDNPdXFlMk1ETDAw
            Y1orNEpXNk8vY095VVFGUjJRSmo4Y00KDcFpV0SUb6sWfCXCwxo8OI++jWWMKIIL
            MJ5lk6YEDuheQtfHKTboPDTFCPMDEesPq1RsCgb8KUpoj4pYiD8Jmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:52:28Z"
    mac: ENC[AES256_GCM,data:LIuDwgrXsi7GYmxwuPxtqoswB1rJ9bnZ9uWj+bbCHQrPpBJK5otWYi4uHN46S/hzefLjXbMlv/kZlcqEbdZgwfxewtmHANdVY2CmUlzC82E3Qg+ELy0rZwA5hlHdISO1aL31udU3w8lJwQfc0gH1wshYmFJoGYq+8xJ9dCivq+g=,iv:fHGL+xx1i06Tsp4i5+NP3QwjE4EIq2qYNOYEURVNDe8=,tag:lOrmeB/Uw53LJ6zAXQM8ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
