apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:8J4Je4NLQmyRyUrDEX469YVJwudIYoIBg0P4SL8uQNg=,iv:vHGxcGOe/aQfSkX0J0YqEa4cqTuYiCKjrpHRNerGLoE=,tag:YExm+onophP+CmtBx7dFbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYkpQRzNzN1hLNUJ4ODlv
            S1hmeDB3VFpRaEs1QVpmQmpJait1bVFaR1ZVCldxS3lKYU1XS2pLRnVuUVNuTkp0
            L3ppdGV4RUFEaHVqWFBEaVAyUGNMcU0KLS0tIFF4cGF3NkIyWWI0dVZaQVdTcXB5
            UWlYczIyNXdFY0paeXVsRFZHT1F6aVEKJ9YeJpwBAbiL0v8Nu59LPFoVJr6Oi/oy
            jQGWuxw0OwjENIVWUQ6zDpsUY/lCcqUHTqLjN9VHK+KajO/vS7EOHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:12:54Z"
    mac: ENC[AES256_GCM,data:Imlj8E0BYvbjykJoOZLv2CQKTxX0edNM6t9UvGTuocpVeJoLjzf3n74WVCYM1iwFO0cYLOCz2pjnEG6SvmNnnRkM1Fq/r0JjZaEfmzlmNlMIOV+cCwOp+ql6gLO4wvYKIjjbTayHstsHP67qsSKDu2bpRx7AJ5zxfBnJ2CYndpA=,iv:eKPmw2hArt9wl/xaT9Zes8YSoaALQ3KZ40wPXQ35HHM=,tag:Q2oYGLCCgJMzoVSvNBjleg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
