apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:unFzkoWE2j5FVZm+e5gqr2N0m1CKvzExTBJYAw9h+poU+IJwPPBIBQ==,iv:f3+T+wl4YXByg+k3aUTs8BI37o1Wl7nKTKoj4hY8/Vo=,tag:84t2cva3KteNycY4lZK+rA==,type:str]
    api-email: ENC[AES256_GCM,data:XVygns+jvWxn3MMylIUnQHjiWxahTHI=,iv:4OqKzAWpdumAhS8hpJJd8kWfYDarWgkkLndSPchKNN4=,tag:VLUvPglbJ693WVrcWj62yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMldmWnFBaWZOSnhmZHJv
            bkhYVTltVzF5MWRKdFpramcrcmhIMWU4T0djCk1qZWFUU3o4MlZ2dnBZYUdHK2lj
            bHlqSW1iclIybEg1UHYwVUJzWFRTd0UKLS0tIEVjZFFHdVpMQVJNTXA0T2IrSVRY
            S1Q3MzNTbXVHRFU0Sy9mYlZNNHhyY00KGVXdAo2LuPYZhBIKaUOIZKS2KvLirF36
            sKTATk54rRtfSV6iRuOzZy41O3KhFYK/JOVVxBt2T4D+1JL/RoFwYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T17:12:54Z"
    mac: ENC[AES256_GCM,data:sh4Lvj9deobyhPhpwqFECstOar0V22WZhoLKo6CnEo+lNfEJjiwBHqIFfUVMdY+Lf6sBMQOjh7tejcnRXS+PMcEg2OMALMa9gicnYSXl1MOtz8myVamddew9Q+1mcvqCbLM2VeYeFkujI2h/n2kdI66QCge4AhBYD/ImUCXs8nY=,iv:UoQ1oeau41kHJBG1Na6+6aVKx3U/aCifWZX/Z+W/1Sc=,tag:6El6t+iovRwCWzFRgIEV7Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
