apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:DFKJHOQJYEk44UmL447HYLzTEjo0XxJ5tdZu4l2t+ZSdlyvyrW7eWw==,iv:X+bgoDIMIocyHf5WUYKomf3SNQoE5Gw+99KRg/57iHw=,tag:siL/Ak0IN7dLTTF/DjXzHQ==,type:str]
    api-email: ENC[AES256_GCM,data:0TMW1mGMrx2Y8LWQ21+yf6QIoojfEuk=,iv:jEjmKtoOxIHvmjGAGTImB3urkKcIjLM+LUPBqv8z4Y4=,tag:sxdvd6VUeodFh4AUS6oH+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVFo5K3JYUGVFNEJ6ZUFR
            RXY3MVY5OGdNMGlURHVaZ0dzUVZLWGdLYXp3CksyNEJuQjNVaHZUUFk5S3ZoVGk4
            ZHVZUW1tL2d5SHZtanRtTDYvaDlGQ3MKLS0tIHVzVkVYTG0rcWtON2pnWEJ4MW1G
            YzNuYWlaMlh3RGxxbnkzMVZGZi9QckUK4aSveHaOCVzIcS+GDd92HaZB7wwHsp8S
            hD0Jt25MZAKnYG7x4dWkeXjfjn6BYgtaos7/fPBaIIAv3gqxEt6TJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T03:52:28Z"
    mac: ENC[AES256_GCM,data:9Yp9VX/KsT7SErmMYjmEeYMgisxzDRrq8p/9gWE+9bmXle9KR/f/zmk7KdWAB0ID2mO+5U/UY4JZA+0uQWdOg8LPmD6Y64Wcxi+Ng7T1ACr2yfC30CcZXVIwhp6Tr7qTenBZgXJXBrTmIKXhGph+pMCYda1zufPVjDi13fFiBlI=,iv:QI4+ZlQv7SqU4qvq4htfQx/aZxrBPbsaefIEmCT1Q8Q=,tag:5G0mNMu9cE4ETo5Ap7slDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
